# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=25)),
                ('github', models.CharField(max_length=50)),
                ('no_hp', models.CharField(max_length=13)),
            ],
        ),
    ]
