# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='no_hp',
            field=models.IntegerField(max_length=13),
        ),
    ]
