# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=20)),
                ('konten', models.TextField()),
            ],
        ),
    ]
