# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artikel_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('keterangan', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='blog.Kategori'),
        ),
    ]
